
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightEXPADD DIV EQUALS EXP ID INT LBRACKET LIST MUL NE RBRACKET REAL SUB\n        statement : statement statement\n                 | statement_expr\n                 | statement_assign\n                 | statement_list_decl\n                 | expression\n        statement_expr : expressionstatement_assign : ID EQUALS expressionstatement_list_decl : LIST ID LBRACKET INT RBRACKET\n        expression : expression ADD expression\n                  | expression SUB expression\n                  | expression MUL expression\n                  | expression DIV expression\n                  | expression EXP expression\n        expression : expression NE expression\n        expression : INT\n                  | REAL\n        expression : IDexpression : ID LBRACKET INT RBRACKET'
    
_lr_action_items = {'ID':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,30,32,],[6,6,-2,-3,-4,-5,-17,19,-15,-16,6,21,21,21,21,21,21,21,-9,-17,-10,-11,-12,-13,-14,-7,-18,-8,]),'LIST':([0,1,2,3,4,5,6,8,9,10,20,21,22,23,24,25,26,27,30,32,],[7,7,-2,-3,-4,-5,-17,-15,-16,7,-9,-17,-10,-11,-12,-13,-14,-7,-18,-8,]),'INT':([0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,29,30,32,],[8,8,-2,-3,-4,-5,-17,-15,-16,8,8,8,8,8,8,8,8,28,-9,-17,-10,-11,-12,-13,-14,-7,31,-18,-8,]),'REAL':([0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,30,32,],[9,9,-2,-3,-4,-5,-17,-15,-16,9,9,9,9,9,9,9,9,-9,-17,-10,-11,-12,-13,-14,-7,-18,-8,]),'$end':([1,2,3,4,5,6,8,9,10,20,21,22,23,24,25,26,27,30,32,],[0,-2,-3,-4,-5,-17,-15,-16,-1,-9,-17,-10,-11,-12,-13,-14,-7,-18,-8,]),'ADD':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[11,-17,-15,-16,-9,-17,-10,-11,-12,-13,11,11,-18,]),'SUB':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[12,-17,-15,-16,-9,-17,-10,-11,-12,-13,12,12,-18,]),'MUL':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[13,-17,-15,-16,13,-17,13,-11,-12,-13,13,13,-18,]),'DIV':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[14,-17,-15,-16,14,-17,14,-11,-12,-13,14,14,-18,]),'EXP':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[15,-17,-15,-16,15,-17,15,15,15,15,15,15,-18,]),'NE':([5,6,8,9,20,21,22,23,24,25,26,27,30,],[16,-17,-15,-16,-9,-17,-10,-11,-12,-13,16,16,-18,]),'EQUALS':([6,],[17,]),'LBRACKET':([6,19,21,],[18,29,18,]),'RBRACKET':([28,31,],[30,32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,1,10,],[1,10,10,]),'statement_expr':([0,1,10,],[2,2,2,]),'statement_assign':([0,1,10,],[3,3,3,]),'statement_list_decl':([0,1,10,],[4,4,4,]),'expression':([0,1,10,11,12,13,14,15,16,17,],[5,5,5,20,22,23,24,25,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement statement','statement',2,'p_statement','compiler.py',70),
  ('statement -> statement_expr','statement',1,'p_statement','compiler.py',71),
  ('statement -> statement_assign','statement',1,'p_statement','compiler.py',72),
  ('statement -> statement_list_decl','statement',1,'p_statement','compiler.py',73),
  ('statement -> expression','statement',1,'p_statement','compiler.py',74),
  ('statement_expr -> expression','statement_expr',1,'p_statement_expr','compiler.py',82),
  ('statement_assign -> ID EQUALS expression','statement_assign',3,'p_statement_assign','compiler.py',89),
  ('statement_list_decl -> LIST ID LBRACKET INT RBRACKET','statement_list_decl',5,'p_statement_list_decl','compiler.py',109),
  ('expression -> expression ADD expression','expression',3,'p_expression_binop','compiler.py',157),
  ('expression -> expression SUB expression','expression',3,'p_expression_binop','compiler.py',158),
  ('expression -> expression MUL expression','expression',3,'p_expression_binop','compiler.py',159),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','compiler.py',160),
  ('expression -> expression EXP expression','expression',3,'p_expression_binop','compiler.py',161),
  ('expression -> expression NE expression','expression',3,'p_expression_ne','compiler.py',221),
  ('expression -> INT','expression',1,'p_expression_number','compiler.py',246),
  ('expression -> REAL','expression',1,'p_expression_number','compiler.py',247),
  ('expression -> ID','expression',1,'p_expression_id','compiler.py',252),
  ('expression -> ID LBRACKET INT RBRACKET','expression',4,'p_expression_list_access','compiler.py',256),
]
