
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightPOWADD ASSIGN DIV DIV_ASSIGN EQ ERROR GE GT IDIV INT LBRACKET LE LIST LPAREN LT MUL NE POW RBRACKET REAL RPAREN SUB VARprogram : statement\n               | expressionstatement : VAR ASSIGN expressionstatement : VAR ASSIGN LIST LBRACKET expression RBRACKETexpression : expression ADD expression\n                 | expression SUB expression\n                 | expression MUL expression\n                 | expression DIV expression\n                 | expression POW expression\n                 | expression NE expressionexpression : LPAREN expression RPARENexpression : VARexpression : INT\n                 | REALexpression : VAR LBRACKET expression RBRACKET'
    
_lr_action_items = {'VAR':([0,5,8,9,10,11,12,13,14,15,28,],[4,17,17,17,17,17,17,17,17,17,17,]),'LPAREN':([0,5,8,9,10,11,12,13,14,15,28,],[5,5,5,5,5,5,5,5,5,5,5,]),'INT':([0,5,8,9,10,11,12,13,14,15,28,],[6,6,6,6,6,6,6,6,6,6,6,]),'REAL':([0,5,8,9,10,11,12,13,14,15,28,],[7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,4,6,7,17,18,19,20,21,22,23,24,27,29,31,],[0,-1,-2,-12,-13,-14,-12,-5,-6,-7,-8,-9,-10,-3,-11,-15,-4,]),'ADD':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[8,-12,-13,-14,8,-12,-5,-6,-7,-8,-9,8,8,8,-11,-15,8,]),'SUB':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[9,-12,-13,-14,9,-12,-5,-6,-7,-8,-9,9,9,9,-11,-15,9,]),'MUL':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[10,-12,-13,-14,10,-12,10,10,-7,-8,-9,10,10,10,-11,-15,10,]),'DIV':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[11,-12,-13,-14,11,-12,11,11,-7,-8,-9,11,11,11,-11,-15,11,]),'POW':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[12,-12,-13,-14,12,-12,12,12,12,12,12,12,12,12,-11,-15,12,]),'NE':([3,4,6,7,16,17,18,19,20,21,22,23,24,26,27,29,30,],[13,-12,-13,-14,13,-12,-5,-6,-7,-8,-9,13,13,13,-11,-15,13,]),'ASSIGN':([4,],[14,]),'LBRACKET':([4,17,25,],[15,15,28,]),'RPAREN':([6,7,16,17,18,19,20,21,22,23,27,29,],[-13,-14,27,-12,-5,-6,-7,-8,-9,-10,-11,-15,]),'RBRACKET':([6,7,17,18,19,20,21,22,23,26,27,29,30,],[-13,-14,-12,-5,-6,-7,-8,-9,-10,29,-11,-15,31,]),'LIST':([14,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'expression':([0,5,8,9,10,11,12,13,14,15,28,],[3,16,18,19,20,21,22,23,24,26,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','parser.py',89),
  ('program -> expression','program',1,'p_program','parser.py',90),
  ('statement -> VAR ASSIGN expression','statement',3,'p_statement_assign','parser.py',94),
  ('statement -> VAR ASSIGN LIST LBRACKET expression RBRACKET','statement',6,'p_statement_list_assign','parser.py',107),
  ('expression -> expression ADD expression','expression',3,'p_expression_operation','parser.py',120),
  ('expression -> expression SUB expression','expression',3,'p_expression_operation','parser.py',121),
  ('expression -> expression MUL expression','expression',3,'p_expression_operation','parser.py',122),
  ('expression -> expression DIV expression','expression',3,'p_expression_operation','parser.py',123),
  ('expression -> expression POW expression','expression',3,'p_expression_operation','parser.py',124),
  ('expression -> expression NE expression','expression',3,'p_expression_operation','parser.py',125),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',133),
  ('expression -> VAR','expression',1,'p_expression_var','parser.py',141),
  ('expression -> INT','expression',1,'p_expression_number','parser.py',147),
  ('expression -> REAL','expression',1,'p_expression_number','parser.py',148),
  ('expression -> VAR LBRACKET expression RBRACKET','expression',4,'p_expression_list_access','parser.py',152),
]
