
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS IDENTIFIER LBRACKET LPAREN MINUS NOTEQUALS NUMBER PLUS POWER RBRACKET RPAREN TIMES\n    expression : term\n               | expression PLUS term\n               | expression MINUS term\n               | assignment\n               | array_element\n               | comparison\n    \n    term : factor\n         | term TIMES factor\n         | term DIVIDE factor\n    \n    factor : NUMBER\n           | IDENTIFIER\n           | LPAREN expression RPAREN\n           | array_element\n    \n    assignment : IDENTIFIER EQUALS expression\n    \n    array_element : IDENTIFIER LBRACKET expression RBRACKET\n    \n    comparison : expression NOTEQUALS factor\n    '
    
_lr_action_items = {'IDENTIFIER':([0,9,10,11,12,13,14,15,16,],[7,7,19,19,19,19,19,7,7,]),'NUMBER':([0,9,10,11,12,13,14,15,16,],[8,8,8,8,8,8,8,8,8,]),'LPAREN':([0,9,10,11,12,13,14,15,16,],[9,9,9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,6,7,8,18,19,20,21,22,23,24,25,27,28,],[0,-1,-4,-5,-6,-7,-11,-10,-2,-11,-13,-3,-16,-8,-9,-14,-12,-15,]),'PLUS':([1,2,3,4,5,6,7,8,17,18,19,20,21,22,23,24,25,26,27,28,],[10,-1,-4,-5,-6,-7,-11,-10,10,-2,-11,-13,-3,-16,-8,-9,10,10,-12,-15,]),'MINUS':([1,2,3,4,5,6,7,8,17,18,19,20,21,22,23,24,25,26,27,28,],[11,-1,-4,-5,-6,-7,-11,-10,11,-2,-11,-13,-3,-16,-8,-9,11,11,-12,-15,]),'NOTEQUALS':([1,2,3,4,5,6,7,8,17,18,19,20,21,22,23,24,25,26,27,28,],[12,-1,-4,-5,-6,-7,-11,-10,12,-2,-11,-13,-3,-16,-8,-9,12,12,-12,-15,]),'RPAREN':([2,3,4,5,6,7,8,17,18,19,20,21,22,23,24,25,27,28,],[-1,-4,-5,-6,-7,-11,-10,27,-2,-11,-13,-3,-16,-8,-9,-14,-12,-15,]),'RBRACKET':([2,3,4,5,6,7,8,18,19,20,21,22,23,24,25,26,27,28,],[-1,-4,-5,-6,-7,-11,-10,-2,-11,-13,-3,-16,-8,-9,-14,28,-12,-15,]),'TIMES':([2,4,6,7,8,18,19,20,21,23,24,27,28,],[13,-13,-7,-11,-10,13,-11,-13,13,-8,-9,-12,-15,]),'DIVIDE':([2,4,6,7,8,18,19,20,21,23,24,27,28,],[14,-13,-7,-11,-10,14,-11,-13,14,-8,-9,-12,-15,]),'EQUALS':([7,],[15,]),'LBRACKET':([7,19,],[16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,9,15,16,],[1,17,25,26,]),'term':([0,9,10,11,15,16,],[2,2,18,21,2,2,]),'assignment':([0,9,15,16,],[3,3,3,3,]),'array_element':([0,9,10,11,12,13,14,15,16,],[4,4,20,20,20,20,20,4,4,]),'comparison':([0,9,15,16,],[5,5,5,5,]),'factor':([0,9,10,11,12,13,14,15,16,],[6,6,6,6,22,23,24,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term','expression',1,'p_expression','parser.py',74),
  ('expression -> expression PLUS term','expression',3,'p_expression','parser.py',75),
  ('expression -> expression MINUS term','expression',3,'p_expression','parser.py',76),
  ('expression -> assignment','expression',1,'p_expression','parser.py',77),
  ('expression -> array_element','expression',1,'p_expression','parser.py',78),
  ('expression -> comparison','expression',1,'p_expression','parser.py',79),
  ('term -> factor','term',1,'p_term','parser.py',88),
  ('term -> term TIMES factor','term',3,'p_term','parser.py',89),
  ('term -> term DIVIDE factor','term',3,'p_term','parser.py',90),
  ('factor -> NUMBER','factor',1,'p_factor','parser.py',99),
  ('factor -> IDENTIFIER','factor',1,'p_factor','parser.py',100),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','parser.py',101),
  ('factor -> array_element','factor',1,'p_factor','parser.py',102),
  ('assignment -> IDENTIFIER EQUALS expression','assignment',3,'p_assignment','parser.py',117),
  ('array_element -> IDENTIFIER LBRACKET expression RBRACKET','array_element',4,'p_array_element','parser.py',132),
  ('comparison -> expression NOTEQUALS factor','comparison',3,'p_comparison','parser.py',139),
]
